In [20]:
import numpy as np
#获取数据
from sklearn.model_selection import train_test_split

In [40]:
# 注释：我已经把数据集改成简单的txt文件了，txt文件就是iris_data.txt，其中，Iris-setosa类用0表示，Iris-versicolor类用1表示，Iris-virginica类用2表示，“,”已经都替换为空格了
dataset = np.loadtxt('iris_data.txt')
# 打印dataset的大小，可以看出来dataset是一个150*5的矩阵
print(dataset.shape)
data = dataset[:,0:4]
target = dataset[:,4]
# data 是4维的特征
# target 是他们的种类
# 可以打印查看这两种数据
# print(data)
# print(target)

(150, 5)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]


In [42]:
X_train, X_test, y_train, y_test = train_test_split( data, target, random_state=2)

In [43]:
X_train

array([[5.5, 2.3, 4. , 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [5. , 2.3, 3.3, 1. ],
       [4.8, 3.4, 1.6, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.2, 3.4, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [6.2, 3.4, 5.4, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [5.4, 3.4, 1.7, 0.2],
       [6.7, 3.1, 5.6, 2.4],
       [6.3, 3.4, 5.6, 2.4],
       [7.6, 3. , 6.6, 2.1],
       [6. , 2.2, 5. , 1.5],
       [4.3, 3. , 1.1, 0.1],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 2.8, 4.1, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 2.7, 4.9, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.7, 2.8, 4.5, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [5.8, 2.6, 4. , 1.2],
       [5.1, 2

In [44]:
y_train

array([1., 2., 1., 1., 2., 1., 0., 2., 0., 1., 0., 0., 0., 2., 2., 2., 0.,
       2., 2., 2., 2., 0., 0., 2., 1., 1., 2., 2., 1., 0., 1., 0., 2., 1.,
       1., 0., 1., 1., 1., 2., 0., 1., 0., 1., 2., 0., 1., 0., 0., 0., 2.,
       2., 0., 0., 2., 2., 1., 2., 1., 1., 2., 0., 2., 2., 2., 0., 2., 0.,
       0., 1., 2., 1., 2., 1., 1., 2., 1., 1., 1., 2., 1., 2., 1., 0., 1.,
       1., 1., 1., 2., 1., 0., 0., 2., 1., 2., 0., 2., 0., 2., 2., 0., 1.,
       0., 2., 1., 0., 2., 1., 0., 0., 1., 0.])

In [45]:
X_test


array([[4.6, 3.4, 1.4, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.4, 1.9, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5. , 3. , 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [4.8, 3. , 1.4, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [6. , 3.4, 4.5, 1.6],
       [6.5, 2.8, 4.6, 1.5],
       [4.5, 2.3, 1.3, 0.3],
       [5.7, 2.9, 4.2, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [5.5, 2.5, 4. , 1.3],
       [6.7, 3. , 5. , 1.7],
       [6.4, 2.9, 4.3, 1.3],
       [6.4, 3.2, 5.3, 2.3],
       [5.6, 2.7, 4.2, 1.3],
       [6.3, 2.3, 4.4, 1.3],
       [4.7, 3.2, 1.6, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.8, 1.9, 0.4],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.9, 3.6, 1.3],
       [7.7, 3.8, 6.7, 2.2],
       [5.4, 3

In [46]:
y_test

array([0., 0., 2., 0., 0., 2., 0., 2., 2., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 2., 1., 1., 1., 2., 1., 1., 0., 0., 2., 0., 2., 2., 0., 1., 2.,
       1., 0., 2., 1.])

In [47]:
X_train.shape

(112, 4)

In [48]:
X_test.shape

(38, 4)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
predict_result = knn.predict(X_test)
#对测试集进行预测
predict_result

In [54]:
knn.score(X_test, y_test)

1.0